package com.dap.blackmud.world;

import java.io.Serializable;

public class Spell implements Serializable {
	private static final long serialVersionUID = 4351021371237308317L;
	
	public static final int 	INVALID_SPELL = 0;
	
	public static final String[][] SPELLS = {
		{"INVALID", 			"0", "false"},
		{"ARMOR", 				"1", "true"},
		{"TELEPORT", 			"2", "true"},
		{"BLESS", 				"3", "true"},
		{"BLINDNESS", 			"4", "true"},
		{"BURNING HANDS", 		"5", "true"},
		{"CALL LIGHTNING", 		"6", "true"},
		{"CHARM PERSON", 		"7", "true"},
		{"CHILL TOUCH", 		"8", "true"},
		{"COLOUR SPRAY", 		"10", "true"},
		{"CONTROL WEATHER", 	"11", "true"},
		{"CREATE FOOD", 		"12", "true"},
		{"CREATE WATER", 		"13", "true"},
		{"CURE BLIND", 			"14", "true"},
		{"CURE CRITIC", 		"15", "true"},
		{"CURE LIGHT", 			"16", "true"},
		{"CURSE", 				"17", "true"},
		{"DETECT EVIL", 		"18", "true"},
		{"DETECT INVISIBLE", 	"19", "true"},
		{"DETECT MAGIC", 		"20", "true"},
		{"DETECT POISON", 		"21", "true"},
		{"DISPEL EVIL", 		"22", "true"},
		{"EARTHQUAKE", 			"23", "true"},
		{"ENCHANT WEAPON",		"24", "true"},
		{"ENERGY DRAIN", 		"25", "true"},
		{"FIREBALL", 			"26", "true"},
		{"HARM", 				"27", "true"},
		{"HEAL", 				"28", "true"},
		{"INVISIBLE", 			"29", "true"},
		{"LIGHTNING BOLT", 		"30", "true"},
		{"LOCATE OBJECT", 		"31", "true"},
		{"MAGIC MISSILE", 		"32", "true"},
		{"POISON", 				"33", "true"},
		{"PROTECT FROM EVIL", 	"34", "true"},
		{"REMOVE CURSE", 		"35", "true"},
		{"SANCTUARY", 			"36", "true"},
		{"SHOCKING GRASP", 		"37", "true"},
		{"SLEEP", 				"38", "true"},
		{"STRENGTH", 			"39", "true"},
		{"SUMMON", 				"40", "true"},
		{"VENTRILOQUATE", 		"41", "true"},
		{"WORD OF RECALL", 		"42", "true"},
		{"REMOVE POISON", 		"43", "true"},
		{"SENSE LIFE", 			"44", "true"},
		{"SNEAK", 				"45", "false"},
		{"HIDE", 				"46", "false"},
		{"STEAL", 				"47", "false"},
		{"BACKSTAB", 			"48", "false"},
		{"PICK LOCK", 			"49", "false"},
		{"KICK", 				"50", "false"},
		{"BASH", 				"51", "false"},
		{"RESCUE", 				"52", "false"},
		{"IDENTIFY", 			"53", "true"},
		{"INFRAVISION", 		"54", "true"},
		{"CAUSE LIGHT", 		"55", "true"},
		{"CAUSE CRITICAL", 		"56", "true"},
		{"FLAMESTRIKE", 		"57", "true"},
		{"DISPEL GOOD", 		"58", "true"},
		{"WEAKNESS", 			"59", "true"},
		{"DISPEL MAGIC", 		"60", "true"},
		{"KNOCK", 				"61", "true"},
		{"KNOW ALIGNMENT", 		"62", "true"},
		{"ANIMATE DEAD", 		"63", "true"},
		{"PARALYSIS", 			"64", "true"},
		{"REMOVE PARALYSIS", 	"65", "true"},
		{"FEAR", 				"66", "true"},
		{"ACID BLAST", 			"67", "true"},
		{"WATER BREATH", 		"68", "true"},
		{"FLY", 				"69", "true"},
		{"CONE OF COLD", 		"70", "true"},
		{"METEOR SWARM", 		"71", "true"},
		{"ICE STORM", 			"72", "true"},
		{"SHIELD", 				"73", "true"},
		{"MASS HEAL", 			"74", "true"},
		{"ELEMENTAL HARMO", 	"75", "true"},
		{"CHARM MONSTER", 		"82", "true"},
		{"CURE SERIOUS", 		"83", "true"},
		{"CAUSE SERIOUS", 		"84", "true"},
		{"REFRESH", 			"85", "true"},
		{"TURN", 				"87", "true"},
		{"LIGHT", 				"89", "true"},
		{"CLEANSING AURA", 		"90", "true"},
		{"CALM", 				"91", "true"},
		{"STONE SKIN", 			"92", "true"},
		{"CONJURE ELEMENTAL", 	"93", "true"},
		{"TRUE SIGHT", 			"94", "true"},
		{"MALIGNANT AURA", 		"96", "true"},
		{"CLINGING MIST", 		"97", "true"},
		{"CACAODEMON", 			"98", "true"},
		{"CHANGE FORM", 		"99", "true"},
		{"UNST MULTI PORT", 	"100", "true"},
		{"GATE", 				"101", "true"},
		{"HELLFIRE", 			"102", "true"},
		{"N BLESSING", 			"103", "true"},
		{"DRAGON BREATH", 		"105", "true"},
		{"WEB", 				"106", "true"},
		{"GOLEM", 				"109", "true"},
		{"FAMILIAR", 			"110", "true"},
		{"CHANGESTAFF", 		"111", "true"},
		{"HOLY WORD", 			"112", "true"},
		{"ENCHANT ARMOR", 		"113", "true"},
		{"PWORD KILL", 			"114", "true"},
		{"PWORD BLIND", 		"115", "true"},
		{"CHAIN LIGHTNING", 	"116", "true"},
		{"PROTECT FROM GOOD", 	"117", "true"},
		{"DETECT GOOD", 		"118", "true"},
		{"LUUKMAARS BARRIER", 	"119", "true"},
		{"CHANGE FORM", 		"120", "true"},
		{"FEEBLEMIND", 			"121", "true"},
		{"SHILLELAGH", 			"122", "true"},
		{"GOODBERRY", 			"123", "true"},
		{"FLAME BLADE", 		"124", "true"},
		{"ANIMAL GROWTH", 		"125", "true"},
		{"INSECT GROWTH", 		"126", "true"},
		{"CREEPING DEATH", 		"127", "true"},
		{"COMMUNE", 			"128", "true"},
		{"ANIMAL SUMMON", 		"129", "true"},
		{"COMPREHEND LANGUAGES","130", "true"},
		{"UNUSED FIRESHIELD", 	"131", "false"},
		{"GODSTONE ATTUNEMENT", "135", "true"},
		{"SPORE CLOUD", 		"136", "true"},
		{"CHARM VEGGIE", 		"137", "true"},
		{"VEGGIE GROWTH", 		"138", "true"},
		{"RIGHTEOUS FURY", 		"139", "true"},
		{"ANIMATE ROCK", 		"140", "true"},
		{"TREE TRAVEL", 		"141", "true"},
		{"TRAVELLING", 			"142", "true"},
		{"ANIMAL FRIENDSHIP", 	"143", "true"},
		{"INVIS TO ANIMALS", 	"144", "true"},
		{"SLOW POISON", 		"145", "true"},
		{"ENTANGLE", 			"146", "true"},
		{"GUST OF WIND", 		"148", "true"},
		{"BARKSKIN", 			"149", "true"},
		{"SUNRAY", 				"150", "true"},
		{"WARP WEAPON", 		"151", "true"},
		{"HEAT STUFF", 			"152", "true"},
		{"FIND TRAPS", 			"153", "true"},
		{"FIRESTORM", 			"154", "true"},
		{"HASTE", 				"155", "true"},
		{"SLOW", 				"156", "true"},
		{"DUST DEVIL", 			"157", "true"},
		{"KNOW MONSTER", 		"158", "true"},
		{"TRANSPORT VIA PLANT",	"159", "true"},
		{"SPEAK WITH PLANT", 	"160", "true"},
		{"SILENCE", 			"161", "true"},
		{"TELEPORT WO ERROR", 	"163", "true"},
		{"PORTAL", 				"164", "true"},
		{"DRAGON RIDE", 		"165", "true"},
		{"MOUNT", 				"166", "true"},
		{"THORN SPRAY",			"167", "true"},
		{"BLADE BARRIER", 		"168", "false"},
		{"DUAL WIELD", 			"169", "false"},
		{"FIRST AID", 			"170", "false"},
		{"SIGN", 				"171", "false"},
		{"RIDE", 				"172", "false"},
		{"SWITCH OPP", 			"173", "false"},
		{"DODGE", 				"174", "false"},
		{"DISARM", 				"175", "false"},
		{"RETREAT", 			"176", "false"},
		{"QUIV PALM", 			"177", "false"},
		{"SAFE FALL", 			"178", "false"},
		{"FEIGN DEATH", 		"179", "false"},
		{"HUNT", 				"180", "false"},
		{"LOCATE TRAP", 		"181", "false"},
		{"SPRING LEAP", 		"182", "false"},
		{"DISARM TRAP", 		"183", "false"},
		{"READ MAGIC", 			"184", "false"},
		{"EVALUATE", 			"185", "false"},
		{"SPY", 				"186", "false"},
		{"DOORBASH", 			"187", "false"},
		{"SWIM", 				"188", "false"},
		{"CONS UNDEAD", 		"189", "false"},
		{"CONS VEGGIE", 		"190", "false"},
		{"CONS DEMON", 			"191", "false"},
		{"CONS ANIMAL", 		"192", "false"},
		{"CONS REPTILE", 		"193", "false"},
		{"CONS PEOPLE", 		"194", "false"},
		{"CONS GIANT", 			"195", "false"},
		{"CONS OTHER", 			"196", "false"},
		{"DISGUISE", 			"197", "false"},
		{"CLIMB", 				"198", "false"},
		{"INSET", 				"199", "false"},
		{"FIRST BREATH WEAPON",	"200", "true"},
		{"GEYSER", 				"200", "true"},
		{"FIRE BREATH", 		"201", "true"},
		{"GAS BREATH", 			"202", "true"},
		{"FROST BREATH", 		"203", "true"},
		{"ACID BREATH", 		"204", "true"},
		{"LIGHTNING BREATH", 	"205", "true"},
		{"LAST BREATH WEAPON", 	"205", "false"},
		{"RESISTANCE", 			"206", "true"},
		{"ARM TRAP", 			"207", "true"},
		{"ARRESTED", 			"208", "false"},
		{"JAILED", 				"209", "false"},
		{"TRIP", 				"215", "false"},
		{"EARTH BORE", 			"216", "false"},
		{"BREWING", 			"217", "false"},
		{"SUN BLIND", 			"218", "true"},
		{"BERSERK", 			"219", "false"},
		{"PALM", 				"220", "false"},
		{"PEEK", 				"221", "false"},
		{"CONS INSECT", 		"222", "false"},
		{"CONS AVIAN", 			"223", "false"},
		{"SHADOW", 				"224", "false"},
		{"ASSASSINATE", 		"225", "false"},
		{"BIND", 				"226", "false"},
		{"IRON FINGER", 		"227", "false"},
		{"EAGLE CLAW", 			"228", "false"},
		{"SUBDUE", 				"229", "false"},
		{"BATTLE MEDITATION", 	"230", "false"},
		{"CHOP", 				"231", "false"},
		{"HEADBUTT", 			"232", "false"},
		{"PLANT", 				"233", "false"},
		{"MOUNTED COMBAT", 		"234", "false"},
		{"SEARCH", 				"235", "false"},
		{"FORAGE", 				"236", "false"},
		{"GOUGE", 				"237", "false"},
		{"GRAPPLE", 			"238", "false"},
		{"MEDITATE", 			"239", "false"},
		{"ARCHERY PROF", 		"240", "false"},
		{"LONG SWORD PROF", 	"241", "false"},
		{"SHORT SWORD PROF", 	"242", "false"},
		{"DAGGER PROF", 		"243", "false"},
		{"HAND AXE PROF", 		"244", "false"},
		{"BATTLE AXE PROF", 	"245", "false"},
		{"STAFF PROF", 			"246", "false"},
		{"POLE AXE PROF", 		"247", "false"},
		{"MACE PROF", 			"248", "false"},
		{"LANCE PROF", 			"249", "false"},
		{"SPEAR PROF", 			"250", "false"},
		{"WHIP PROF", 			"251", "false"},
		{"COMBAT OFF", 			"252", "false"},
		{"COMBAT DEF", 			"253", "false"},
		{"MAX EXIST SPELL", 	"240", "false"}
	};
	
	private String spellName = SPELLS[INVALID_SPELL][0];
	private int spellNum = INVALID_SPELL;
	private boolean valid = SPELLS[INVALID_SPELL][2].equals("true");
	
	public Spell(int spellNum) {
		String[] spellInfo = SPELLS[findSpellIndex(spellNum)];
		setSpellInfo(spellInfo);
	}
	
	public Spell(String[] spellInfo) {
		setSpellInfo(spellInfo);
	}
	
	private void setSpellInfo(String[] spellInfo) {
		this.spellName = spellInfo[0];
		this.spellNum = Integer.parseInt(spellInfo[1]);
		this.valid = spellInfo[2].equals("true");
	}
	
	private int findSpellIndex(int spellNum) {
		for(int i = 0; i < SPELLS.length; i++) {
			if(Integer.parseInt(SPELLS[i][1]) == spellNum)
				return i;
		}
		return 0;
	}

	public String getName() {
		return spellName;
	}

	public int getNum() {
		return spellNum;
	}

	public boolean isValid() {
		return valid;
	}
}
